version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - IoTS-Project2
      
  pg4admin:
    image: dpage/pgadmin4
    container_name: pg4admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - IoTS-Project2
    depends_on:
      - postgres
      
   sensor:
    image: sensor
    container_name: sensor
    networks:
      - IoTS-Project2
    depends_on:
      - postgres
    
    mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - IoTS-Project2
      
    nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - IoTS-Project2
      
    filter:
    image: filter
    container_name: filter
    networks:
      - IoTS-Project2
    depends_on:
      - mosquitto
      - nats
      
    dashboard:
    image: dashboard
    container_name: dashboard
    networks:
      - IoTS-Project2
    depends_on:
      - nats
      - filter
      
    influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE: setup
      - DOCKER_INFLUXDB_INIT_USERNAME: user
      - DOCKER_INFLUXDB_INIT_PASSWORD: weather1234
      - DOCKER_INFLUXDB_INIT_ORG: weather.org
      - DOCKER_INFLUXDB_INIT_BUCKET: weather_data
      - DOCKER_INFLUXDB_INIT_RETENTION: 30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - IoTS-Project2
      
    grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - INFLUXDB_URL: http://influxdb:8086
      - INFLUXDB_ORG: weather.org
      - INFLUXDB_BUCKET: weather_data
      - GF_INFLUXDB_TOKEN: mytoken
      - GF_LOG_LEVEL: debug
      - GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - IoTS-Project2
      
    manager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    volumes:
      - /tmp/manager_data:/ekuiper-manager/data
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    depends_on:
      - mosquitto
    networks:
      - IoTS-Project2
    
    ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - /tmp/data:/kuiper/data
      - /tmp/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:8883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    depends_on:
      - mosquitto
    networks:
      - IoTS-Project2
      
    fakeEkuiper:
    image: fake-ekuiper
    container_name: fake-ekuiper
    networks:
      - IoTS-Project2
    depends_on:
      - mosquitto
      - sensor
      
    command_server:
    image: command_image
    container_name: command_server
    ports:
      - "8888:8080"
    networks:
      - IoTS-Project2
      
    web_page:
    image: web_page
    container_name: web_page
    ports:
      - "80:80"
    networks:
      - IoTS-Project2
  
networks:
  IoTS-Project2:
    driver: bridge